services:
  laravel-rc:
    build:
      context: docker
    container_name: laravel-rc
    ports:
      - "[::]:${PHP_SUPERVISOR_PORT:-9009}:9009"
      - "[::]:${RUNNER_HTTP_PORT:-8080}:8080"
      - "[::]:${RUNNER_EXT_RPC_PORT:-6001}:6001"
      - "[::]:${RUNNER_HEALTHCHECK_PORT:-2115}:2115"
    restart: always
    command: sh -c "docker-php-entrypoint supervisord -c /etc/supervisor/supervisord.conf && tail -f /var/log/supervisor/supervisord.log"
    platform: linux/amd64
    tty: true
    stdin_open: true
    networks:
      - api-network
    volumes:
      - ./app:/app
      - ./docker/supervisord:/etc/supervisor/conf.d
    dns:
      - ${DOCKER_DNS_1:-1.1.1.1}
      - ${DOCKER_DNS_2:-8.8.8.8}

networks:
  api-network:
    driver: bridge